/// <reference types="react-native-css/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css. If you need to move or disable this file, please see the documentation.

// Fallback for editors that don't resolve CSS side-effect imports via `bundler` mode
declare module "*.css" {}